### ISSUE TITLE
Alloy widget installation issue.

### ISSUE THREAD

**Issue by iskugor** [FokkeZB/gittio#104]
Hi.

I tried to install Alloy widget with Gittio but it was installed in weird way. Seems like widget code was reverted to first commit.

To see issue, create empty Alloy project and run: gittio install StarRating

Go to "widgets" directory and check out source files in StarRating directory.

They should be identical to this (first) commit: https://github.com/jbeuckm/AlloyStarRatingWidget/commit/60ace4b77b4b3bbbd0594ea4b71f81e08e827aaf

while latest code can be found here: https://github.com/jbeuckm/AlloyStarRatingWidget

My Gittio version is 0.5.5.

If you need more information from me please let me know.

**Comment by FokkeZB** [comment]
gittio will install the first commit in which it found the version. In this case the version has been unchanged all the time since that commit so it will install that.

If you want master, then install with `gittio install StarRating@master`

**Comment by iskugor** [comment]
Ahhh, ok, thanks :+1:
