### ISSUE TITLE
`platform/android` folder in commonjs modules

### ISSUE THREAD

**Issue by falkolab** [FokkeZB/gittio#106]
As described in `hyperloop` guide I can add `jar` files to the `platform/android` folder. I looking for possibility to include `jar` to the `commonjs` module packaged with `titaniumifier` and install it with `gittio`.
I can’t find any guidlines about packaging commonjs modules.
Is it feature of titaniumifier plugin?

**Comment by FokkeZB** [comment]
Titanium CommonJS modules are in fact iOS/Android modules with no native code. They were never fully documented. [Titaniumifier](https://github.com/smclab/titaniumifier/wiki) by @yuchi is a great tool to turn a a set of CommonJS files into a Titanium CommonJS module. If it doesn't include the platform folder atm, please ask him to add that feature.

**Comment by yuchi** [comment]
Is including the `platform` did enough? If it is I'll add it ASAP.

**Comment by yuchi** [comment]
*~~did~~ dir

**Comment by FokkeZB** [comment]
Think so

**Comment by falkolab** [comment]
For Android answer is yes.
