### ISSUE TITLE
Module installation error on node 4.2.3 

### ISSUE THREAD

**Issue by nazrdogan** [FokkeZB/gittio#108]
I m using Node 4.2.3 When trying to install I m getting this error. 

       [ERROR] gittio requires the global Titanium CLI: [sudo] npm install -g titanium
 
But I m aldready installed Titanium.

        titanium -v
        node) sys is deprecated. Use util instead.
        5.0.5

 I look at gittio source code timodules.list function returns null

**Comment by FokkeZB** [comment]
Mm, maybe because of that error timodules isn't able to read the JSON result from the Ti CLI. Let me check if we need to update the Ti CLI to work with 4.2.x still or if this has already been fixed.

**Comment by FokkeZB** [comment]
Could you reinstall the Ti CLI? I run node 4.2.3 as well but I don't get that warning when I run `ti -v`

**Comment by FokkeZB** [comment]
See https://jira.appcelerator.org/browse/TIMOB-19133

**Comment by nazrdogan** [comment]
@FokkeZB   I reinstall Ti CLI and Gittio but  same result. :(

**Comment by FokkeZB** [comment]
Could you try to delete your local npm cache (`sudo rm -rf ~/.npm`) and then install again?

**Comment by nazrdogan** [comment]
I tried but same :(

**Comment by FokkeZB** [comment]
Weird. Could you do a code search on the titanium dir (probably `/usr/local/lib/node_modules`) to see where sys is used? Search for both `"sys"` and `'sys'`.

**Comment by nazrdogan** [comment]
it cannot  find anything

**Comment by nazrdogan** [comment]
I open Titanium npm modules on  text editor. and search 
       (node) sys is deprecated. Use util instead.
 nothing found .its really weird .where is it come

**Comment by nazrdogan** [comment]
its only found on test files 

        /usr/local/lib/node_modules/titanium/node_modules/node-appc/node_modules/.bin/uglifyjs:
    5  
    6  var UglifyJS = require("../tools/node");
    7: var sys = require("util");
    8  var yargs = require("yargs");
    9  var fs = require("fs");

      /usr/local/lib/node_modules/titanium/node_modules/node-appc/node_modules/request/node_modules/http-signature/node_modules/asn1/tst/ber/writer.test.js:
    2  
    3  var test = require('tap').test;
    4: var sys = require('sys');
    5  
    6  ///--- Globals

        /usr/local/lib/node_modules/titanium/node_modules/node-appc/node_modules/uglify-js/bin/uglifyjs:
    5  
    6  var UglifyJS = require("../tools/node");
    7: var sys = require("util");
    8  var yargs = require("yargs");
    9  var fs = require("fs");

          /usr/local/lib/node_modules/titanium/node_modules/node-appc/node_modules/uglify-js/node_modules/uglify-to-browserify/index.js:
      15    if (cache[file]) return makeStream(cache[file])
     16    var uglify = require(file)
      17:   var src = 'var sys = require("util");\nvar MOZ_SourceMap = require("source-map");\nvar UglifyJS = exports;\n' + uglify.FILES.map(function (path) { return fs.readFileSync(path, 'utf8') }).join('\n')
      18  
        19    var ast = uglify.parse(src)

    /usr/local/lib/node_modules/titanium/node_modules/request/node_modules/http-signature/node_modules/asn1/tst/ber/writer.test.js:
    2  
    3  var test = require('tap').test;
    4: var sys = require('sys');
    5  
    6  ///--- Globals

    5 matches across 5 files

**Comment by FokkeZB** [comment]
Yeah, very strange. I've found that as well with another user and reported the issue:
https://jira.appcelerator.org/browse/CLI-907

**Comment by nazrdogan** [comment]
•	sudo rm -rf ~/.appcelerator
•	sudo rm -rf ~/.titanium
•	sudo npm uninstall -g titanium
•	sudo npm uninstall -g alloy
•	sudo npm uninstall -g acs
•	sudo npm uninstall -g appcelerator
•	sudo npm install -g appcelerator
•	appc use latest
•	appc setup
•	sudo npm install -g alloy
*       sudo npm install -g titanium  

 Now its solved my problem.

**Comment by FokkeZB** [comment]
haha, but now we still don't know where sys was used ;)

**Comment by nazrdogan** [comment]
yes :)  We cannot know anymore

**Comment by cdrx** [comment]
Did you have TiShadow installed?

**Comment by nazrdogan** [comment]
yes . its give me 
(node) sys is deprecated. Use util instead.

**Comment by cdrx** [comment]
If you uninstall it (or update to tishadow master) the sys / util warning will go away.

**Comment by nazrdogan** [comment]
Now Titanium not giving util warning .But Tishadow gives. And they are different modules. How can it possible ?

**Comment by cdrx** [comment]
TiShadow installs a hook into your ~/.titanium/config.json file that appc runs

**Comment by nazrdogan** [comment]
Hmm now I understand ,thank guy :)
