### ISSUE TITLE
gittio cli won't install packages 

### ISSUE THREAD

**Issue by cdrx** [FokkeZB/gittio#109]
I can't get gittio to install packages any more. I'm not sure when it stopped working. 

    $ gittio install nl.fokkezb.loading
    [ERROR] gittio requires the global Titanium CLI: [sudo] npm install -g titanium
    
    $ sudo npm install -g titanium
    /usr/local/bin/ti -> /usr/local/lib/node_modules/titanium/bin/titanium
    /usr/local/bin/titanium -> /usr/local/lib/node_modules/titanium/bin/titanium
    /usr/local/lib
    └── titanium@5.0.5
    
    $ which titanium
    /usr/local/bin/titanium
    
    $ titanium --version
    5.0.5
    
    $ gittio install nl.fokkezb.loading
    [ERROR] gittio requires the global Titanium CLI: [sudo] npm install -g titanium    

Any ideas how I can debug this?

**Comment by FokkeZB** [comment]
Mmm, I don't directly check for the Titanium CLI, but assume that if `timodules` has no result it couldn't find it. Could you maybe add some logging to debug around this? Perhaps there are other circumstances where it would have no result.

https://github.com/FokkeZB/gittio/blob/92f93352c187074f8b3287896e860525fc1d55ca/lib/config.js#L95

**Comment by cdrx** [comment]
The problem I'm having is caused by CLI-907 @ https://jira.appcelerator.org/browse/CLI-907 

Not a bug with gittio
