### ISSUE TITLE
Cannot use gittio with nvm

### ISSUE THREAD

**Issue by davidbnk** [FokkeZB/gittio#111]
I installed Node.js through nvm, and I get the following error:

    $ node -v
    v5.3.0
    
    $ gittio install <module>
    [ERROR] gittio requires the global Titanium CLI: [sudo] npm install -g titanium

    $ npm install -g titanium
    /Users/user/.nvm/versions/node/v5.3.0/bin/ti -> /Users/user/.nvm/versions/node/v5.3.0/lib/node_modules/titanium/bin/titanium
    /Users/user/.nvm/versions/node/v5.3.0/bin/titanium -> /Users/user/.nvm/versions/node/v5.3.0/lib/node_modules/titanium/bin/titanium
    /Users/user/.nvm/versions/node/v5.3.0/lib
    └── titanium@5.0.5 

    $ gittio install <module>
    [ERROR] gittio requires the global Titanium CLI: [sudo] npm install -g titanium

**Comment by FokkeZB** [comment]
Could it be that you have tishadow installed? It used the sys module which causes a warning in Node 4 or later which corrupts the Titanium json output that ultimately can cause this error: https://github.com/FokkeZB/gittio/issues/109

**Comment by davidbnk** [comment]
Yes I do have tishadow installed. Thanks for the feedback
