### ISSUE TITLE
Add .gittiorc support

### ISSUE THREAD

**Issue by gregpardo** [FokkeZB/gittio#112]
Per project configuration should be able to be set in a .gittiorc file. Parameters that are used with cli should override any rc config. Will consider doing this if there is other people who could find it useful

**Comment by FokkeZB** [comment]
could you provide some usage examples? sounds interesting

**Comment by yuchi** [comment]
See https://docs.npmjs.com/files/npmrc.

I’m not suggesting to follow the format of `.npmrc` (which is `init`-like) but to follow its folder semantics.

**Comment by gregpardo** [comment]
Also this..

http://bower.io/docs/config/

Here would be my current usage example for a .gittiorc file. It would look something like this. Just using alloyBase as an example property here.

```json
{
"alloyBase": "src"
}
```

Then this relieves the user from having to type
```
gittio install com.etc.etc -b src
```

They can not simply type this while in the project directory
```
gittio install com.etc.etc
```

**Comment by FokkeZB** [comment]
Looks good! Either of you want to do a PR?

**Comment by yuchi** [comment]
Super cool module that would accelerate things a lot: https://www.npmjs.com/package/rc
