### ISSUE TITLE
Usage as a module in a node app

### ISSUE THREAD

**Issue by AndreaVitale** [FokkeZB/gittio#117]
Hi fokke, I'm unable to use your gittio as a module in a nodejs app.
When I try to install a package I have this error:

```
Andreas-MacBook-Pro:test_gittio Andrea$ node index.js install a.test.for.gittio
[INFO]  a.test.for.gittio searching...
[ERROR] a.test.for.gittio error contacting registry: undefineda.test.for.gittio?action=install
```

I attach a simple node app that shows the error. Was my fault? I have to do some configuration in order to use it?

Thanks!

[test_gittio.zip](https://github.com/FokkeZB/gittio/files/521394/test_gittio.zip)

**Comment by FokkeZB** [comment]
Thanks for finding out about this. I just fixed it in master. Could you verify?

**Comment by AndreaVitale** [comment]
Is working correctly, thank you!
