### ISSUE TITLE
`gittio install` changes tiapp.xml

### ISSUE THREAD

**Issue by Bertuzb** [FokkeZB/gittio#119]
Reproduce: Run `gittio install`, the file `tiapp.xml` receives some indentation and is then saved (presuming the indentation on the "<modules>" tag is different). IMHO, it's best to not change the file at all but only read from it.

**Comment by FokkeZB** [comment]
Hi @Bertuzb,

`gittio install <module>` will add the module you install to the `tiapp.xml`. Do you see it also change the file when it's not adding a module (e.g. running `gittio install` to install already declared module dependencies or when installing an Alloy widget?)

**Comment by Bertuzb** [comment]
yes, I was just installing modules that were predefined in tiapp.xml. It basically just indented the `<module>` tag after installation

**Comment by FokkeZB** [comment]
@Bertuzb mm, that [shouldn't happen](https://github.com/FokkeZB/gittio/blob/master/lib/tiapp.js#L60)

Are you sure nothing changes. Not even the module version or so?

**Comment by Bertuzb** [comment]
Im not at work atm, but i'm fairly sure it only indented the lines. I'll get back to this next week.

**Comment by Bertuzb** [comment]
Here a differential screenshot of the exact lines that were changed:
<img width="587" alt="schermafbeelding 2017-03-28 om 10 13 34" src="https://cloud.githubusercontent.com/assets/10498595/24395313/860228d6-139f-11e7-998e-322d96419bcd.png">

with only calling `gittio install`

**Comment by FokkeZB** [comment]
If you don't mind I'll leave this open for now. I understand it's frustrating, but I don't have the bandwidth to look at it atm.

**Comment by Bertuzb** [comment]
sure. I'll see if I can create a pull request when I have some time available

**Comment by Bertuzb** [comment]
Removing line https://github.com/FokkeZB/gittio/blob/30803edceb50d5c61cc7ae121b08fdd462b9c726/lib/gittio.js#L329 seems to fix it

**Comment by FokkeZB** [comment]
@Bertuzb indeed, that in turn calls https://github.com/FokkeZB/gittio/blob/master/lib/tiapp.js#L49 where I see the issue. I've fixed it in master. Could you try `[sudo] npm i -g gittio`?

**Comment by Bertuzb** [comment]
confirmed fixed for `gittio@0.6.4`

**Comment by FokkeZB** [comment]
@Bertuzb I didn't release it yet sorry, so you need to do `[sudo] npm i -g fokkezb/gittio`
