### ISSUE TITLE
Gittio detects notice as error

### ISSUE THREAD

**Issue by jakejdavis** [FokkeZB/gittio#120]
When trying to install a module gittio returns:
```
[ERROR] Error running timodules: NOTICE: Longjohn is known to cause CPU usage due to its extensive data collection during runtime.
It generally should not be used in production applications.
(node:17784) DeprecationWarning: sys is deprecated. Use util instead.
 
[ERROR] You need either the Titanim or Appcelerator CLI to be installed:

        [sudo] npm i -g titanium appcelerator
```
even though both titanium and appcelerator are installed, it looks like it is detecting the notice of `Longjohn is known to cause CPU usage due to its extensive data collection during runtime.` as an error and quiting.

**Comment by FokkeZB** [comment]
This is an error in the timodules dependency:
https://github.com/FokkeZB/gittio/blob/c442405fd02cbea0cd33b0ae7edcc6670cef6021/lib/config.js#L93-L124

@jakejdavis could you report this at https://github.com/dbankier/timodules/issues ?
