### ISSUE TITLE
No distributable available

### ISSUE THREAD

**Issue by Bertuzb** [FokkeZB/gittio#121]
This may or may not be an issue with gittio:

Take a look at this module: http://gitt.io/component/ti.cloudpush

When running the command `gittio install ti.cloudpush` I get:

```
[INFO]  ti.cloudpush searching...
[ERROR] ti.cloudpush:commonjs no distributable available
[ERROR] ti.cloudpush:ios no distributable available
[ERROR] ti.cloudpush:android no distributable available
```

It confused me because the gitt.io website seems to pick up the module correctly.

Please close this issue if the ti.cloudpush module itself is to blame.

**Comment by FokkeZB** [comment]
Hi @Bertuzb, when you see the download column saying N/A you'll run into this. The CLI's install only works when gitTio has found a download to install.
