### ISSUE TITLE
Cannot install com.rkam.swiperefreshlayout

### ISSUE THREAD

**Issue by turbomonkey** [FokkeZB/gittio#92]
I cannot install com.rkam.swiperefreshlayout using gittio CLI.

command:
gittio install com.rkam.swiperefreshlayout

error:
[INFO]  com.rkam.swiperefreshlayout searching...
[ERROR] com.rkam.swiperefreshlayout:commonjs no distributable available
[ERROR] com.rkam.swiperefreshlayout:android no distributable available
[ERROR] com.rkam.swiperefreshlayout:ios no distributable available

I am going to try doing it from zip but thought you should know.

Thanks

**Comment by FokkeZB** [comment]
That is because unfortunately, forked repositories are not searchable at the moment:

https://github.com/iskugor/Ti.SwipeRefreshLayout/search?q=swiperefreshlayout&type=Code
